pdfcpu stamp add -m text -- "CD/%p" "pos:br, scale:0.04, rot:0" "./printable-3x3-tiled-landscape/bits-wilp-sem6-computing-and-design-ppts-consolidated-3x3-landscape-non-indexed.pdf" "./printable-3x3-tiled-landscape/bits-wilp-sem6-computing-and-design-ppts-consolidated-3x3-landscape.pdf"
pdfcpu stamp add -m text -- "DD/%p" "pos:br, scale:0.04, rot:0" "./printable-3x3-tiled-landscape/bits-wilp-sem6-database-design-ppts-consolidated-3x3-landscape-non-indexed.pdf" "./printable-3x3-tiled-landscape/bits-wilp-sem6-database-design-ppts-consolidated-3x3-landscape.pdf"
pdfcpu stamp add -m text -- "SDP/%p" "pos:br, scale:0.04, rot:0" "./printable-3x3-tiled-landscape/bits-wilp-sem6-software-design-principals-ppts-consolidated-3x3-landscape-non-indexed.pdf" "./printable-3x3-tiled-landscape/bits-wilp-sem6-software-design-principals-ppts-consolidated-3x3-landscape.pdf"
pdfcpu stamp add -m text -- "SIA/%p" "pos:br, scale:0.04, rot:0" "./printable-3x3-tiled-landscape/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-3x3-landscape-non-indexed.pdf" "./printable-3x3-tiled-landscape/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-3x3-landscape.pdf"

pdfcpu stamp add -m text -- "CD/%p" "pos:br, scale:0.04, rot:0" "./printable-2x3-tiled/bits-wilp-sem6-computing-and-design-ppts-consolidated-2x3-non-indexed.pdf" "./printable-2x3-tiled/bits-wilp-sem6-computing-and-design-ppts-consolidated-2x3.pdf"
pdfcpu stamp add -m text -- "DD/%p" "pos:br, scale:0.04, rot:0" "./printable-2x3-tiled/bits-wilp-sem6-database-design-ppts-consolidated-2x3-non-indexed.pdf" "./printable-2x3-tiled/bits-wilp-sem6-database-design-ppts-consolidated-2x3.pdf"
pdfcpu stamp add -m text -- "SDP/%p" "pos:br, scale:0.04, rot:0" "./printable-2x3-tiled/bits-wilp-sem6-software-design-principals-ppts-consolidated-2x4-non-indexed.pdf" "./printable-2x3-tiled/bits-wilp-sem6-software-design-principals-ppts-consolidated-2x4.pdf"
pdfcpu stamp add -m text -- "SIA/%p" "pos:br, scale:0.04, rot:0" "./printable-2x3-tiled/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-2x3-non-indexed.pdf" "./printable-2x3-tiled/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-2x3.pdf"

pdfcpu stamp add -m text -- "CD/%p" "pos:br, scale:0.04, rot:0" "./printable-2x2-tiled-landscape/bits-wilp-sem6-computing-and-design-ppts-consolidated-2x2-landscape-non-indexed.pdf" "./printable-2x2-tiled-landscape/bits-wilp-sem6-computing-and-design-ppts-consolidated-2x2-landscape.pdf"
pdfcpu stamp add -m text -- "DD/%p" "pos:br, scale:0.04, rot:0" "./printable-2x2-tiled-landscape/bits-wilp-sem6-database-design-ppts-consolidated-2x2-landscape-non-indexed.pdf" "./printable-2x2-tiled-landscape/bits-wilp-sem6-database-design-ppts-consolidated-2x2-landscape.pdf"
pdfcpu stamp add -m text -- "SDP/%p" "pos:br, scale:0.04, rot:0" "./printable-2x2-tiled-landscape/bits-wilp-sem6-software-design-principals-ppts-consolidated-2x2-landscape-non-indexed.pdf" "./printable-2x2-tiled-landscape/bits-wilp-sem6-software-design-principals-ppts-consolidated-2x2-landscape.pdf"
pdfcpu stamp add -m text -- "SIA/%p" "pos:br, scale:0.04, rot:0" "./printable-2x2-tiled-landscape/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-2x2-landscape-non-indexed.pdf" "./printable-2x2-tiled-landscape/bits-wilp-sem6-statistical-inference-and-applications-ppts-consolidated-2x2-landscape.pdf"
